<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Tmmd;

class TmmdSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
          Tmmd::create([
        'title' => 'TNI Manunggal Membangun Desa (TMMD) ke-107 tahun 2020 di Desa Bumiwangi dan Mekarlaksana Kecamatan Ciparay Kabupaten Bandung',
        'body' => 'Pada tanggal 10 Maret 2020 Dandim 0624 / Kab. Bandung mendampingi Danrem  062 / TN meninjau lokasi pelaksanaan TMMD ke 107 TA. Dandim 0624 Kabupaten Bandung, Letkol Infanteri Donny Ismuali Bainur S. Hub. Int, M.A.S.S.S, didampingi Danramil 2408 Wilayah Ciparay Kapten Infanteri Ujang Mulyana beserta Kapten Rudi Pasiter dan Mayor Sutisna S.Pdi. Melakukan peninjauan langsung  persiapan pelaksanaan TNI Manunggal Membangun Desa (TMMD) ke-107 tahun 2020 di Desa Bumiwangi dan Mekarlaksana Kecamatan Ciparay Kabupaten Bandung.Dandim 0624 Kabupaten Bandung, Letkol Infanteri Donny Ismuali Bainur S. Hub. Int, M.A.S.S.S, didampingi Danramil 2408 Wilayah Ciparay Kapten Infanteri Ujang Mulyana beserta Kapten Rudi Pasiter dan Mayor Sutisna S.Pdi. Melakukan peninjauan langsung  persiapan pelaksanaan TNI Manunggal Membangun Desa (TMMD) ke-107 tahun 2020 di Desa Bumiwangi dan Mekarlaksana Kecamatan Ciparay Kabupaten Bandung. Adapun tema giat TMMD ke - 107 tahun 2020  yaitu  Pengabdian untuk Negeri dan Wujud kedekatan TNI dan rakyat  tanpa batas . Bersama rakyat TNI kuat, bersama rakyat  kita bisa wujudkan impian.
        
        Giat TMMD ke - 107 ini  dilaksanakan dari tanggal 16 Maret 2020 sampai dengan 14 April 2020. Dengan agenda kegiatan tidak hanya meliputi pelaksanaan fisik tetapi ada beberapa kegiatan tambahan non fisik. Pelaksanaan TMMD ke - 107 ini diantaranya membangun akses jalan baru sepanjang 2. 330 m dari Kampung Beko Desa Bumiwangi sampai Kampung Cisalak Desa Mekarlaksana Kecamatan Ciparay. Selain itu ada juga kegiatan penanaman bibit pohon dalam upaya  penghijauan di Kampung Beko Rw. 04 di Komplek Kodiklat Desa Bumiwangi oleh Ketua Persit KCK Kodim 0624/ Kabupaten Bandung Ny. Yulianty Hakim Donny Ismuali Bainuri. Dalam pelaksanaannya personel yang terlibat sebanyak 250 orang meliputi unsur TNI hingga Polri. Sasaran utama dari kegiatan TMMD ke-107di bawah Kodim 0624/Kabupaten Bandung ini adalah jalan, rutilahu dan MCK. Jalan yang diperkerasnya sepanjang 2,3 Km, rutilahu yang diperbaiki sebanyak 4 unit dan MCK yang dibuat 2 unit. Jalan yang diperkeras ini menghubungkan Desa Bumiwangi dan Desa Mekarlaksana. Selain sasaran utama fisik kegiatan TMMD ke - 107 ini memiliki sasaran non fisik dalam bentuk pembuatan green house, penyebaran / penanaman bibit pohon, serta sosialisasi tentang pandemi covid 19 kepada masyarakat setempat. 
        
        Menurut Kolonel Inf.  F.X. Sri Wellyanto Kasih Kapendam Iii/Siliwangi Hingga pelaksanaan TMMD ke-107 tahun 2020 selesai  yang di gelar di Wilayah Kodim 0624/Kabupaten Bandung, saat ini secara bergotong royong telah menyelesaikan pembangunan jalan tembus sepanjang 2800 M dengan lebar 4 meter, yang menghubungkan Desa Bumiwangi dan Mekarlaksana Kecamatan Ciparay Kabupaten Bandung atau Lingkar Ciparay. Jalan baru tersebut bisa dimanfaatkan sebagai jalur alternatif ketika Jalan Raya Laswi Ciparay mengalami kemacetan terutama di titik depan Alun-alun Ciparay. Selain untuk menghubungkan tiga desa yaitu, Bumiwangi, Mekarlakasan dan Desa Sagara Cipta di Ciparay, Jalan Lingkar Nagreg ini nantinya akan menjadi jalur alternatif apabila ada kepadatan lalu lintas di depan Alun-alun Ciparay. Dengan adanya jalur alternatif tersebut, kemacetan di titik itu bisa terurai, sekaligus dapat membuka akses kampung yang tadinya tersisolir nanti dengan dibukanya Jalur Lingkar Ciparay maka akan menggerakkan laju perekonomian masyarakat. Giat TMMD ke - 107  Tahun 2020 yang dilaksanakan di Desa Bumiwangi dan Desa Mekarlaksana, Kec. Ciparay resmi ditutup yang dilaksanakan di Rumah Jabatan Bupati Bandung H. Dadang M Naser di Soreang pada Selasa (14/04/2020). Bupati Bandung Dadang M Naser juga sangat mengapresiasi jajaran TNI yang telah membantu Pemkab Bandung dalam percepatan pembangunan melalui TNI Manunggal Membangun Desa (TMMD) ke-107. Menurutnya kegiatan TMMD sangat efektif dalam meningkatkan pertumbuhan ekonomi masyarakat Kabupaten Bandung. Serta meningkatkan disiplin masyarakat dalam memutus rantai Covid - 19 pada saat itu dengan gencar melaksanakan sosialisasi pencegahan penyebaran Covid-19. (Source : Portal Kabupaten Bandung).',
        'img' => 'https://1.bp.blogspot.com/-E1e9_iKizzw/YFsJwciJsWI/AAAAAAAAAiY/Mpi6u__Jebk-pban4VA3VOxRV5C2zGKyACLcBGAsYHQ/s263/no%2Bimage.JPG',
        'label' => 'Tmmd',
    ]);


    Tmmd::create([
        'title' => 'TMMD ke-113 di Desa Pulosari Kecamatan Pangalengan Wilayah Kodim 0624/Kab. Bandung TA 2022',
        'body' => 'Kegiatan TMMD terpusat ke-113 di Desa Pulosari Kec. Pangalengan wilayah Kodim 0624/Kab. Bandung, kegiatan TMMD dilaksanakan mulai tanggal 11 Mei 2022 s.d 10 Juni 2022, dengan melibatkan personel 1 SSK satuan TNI gabungan 150 orang. Dalam kegiatan persiapan dan pembukaan dilaksanakan penandatanganan berita acara serah terima pekerjaan TMMD terpusat ke- 113 Tahun 2022 (Dandim 0624 dan Bupati Kab. Bandung),  yang diwakili Asda 1 Dr. H. Erick Djuriara Ekananta, M. Si., serta penyerahan secara simbolis fasilitas barang kepada masyarakat, serta meninjau gelar produk dan mobil pelayanan. Dalam TMMD ke - 113 ini sasaran fisik berupa perkerasan jalan sepanjang 5 x 2045 meter, penbuatan TPT 2 titik dan pembuatan platdecker 6 titik serta sasaran tambahan pengerjaan Rehab rumah 1 unit. Sedangkan sasaran non fisik berupa penyuluhan posyandu, posbindu, stunting, KB Kesehatan dan penyuluhan bahaya kebakaran serta pencegahan bencana alam. Program TMMD yang ke 113 tahun 2022 diharapkan bisa menggerakkan roda perekonomian warga setempat khususnya Desa Pulosari dan Desa Margamekar Kec. Pangalengan, Kemanunggalan TNI dan Rakyat diharapkan makin terjalin dengan lebih baik lagi di Desa itu sendiri melalui silaturahmi, silih asah, silih asih silih asuh dengan berbagai unsur di Desa Polusari dan Margamekar. Peran serta masyarakat diharapkan dapat memacu perekonomian Desa khususnya Desa Pulosari dan Margamekar menjadi Desa Wisata.
        
        Berdasarkan data Pemerintahan Desa Pulosari, sebagian besar lahan di wilayah Desa Pulosari digunakan sebagai lahan perkebunan. yakni sebesar 51,17% dari keseluruhan penggunaan lahan. Dengan adanya tata guna lahan perkebunan yang begitu luas, hal tersebut menunjukkan masyarakat Desa Pulosari mayoritas masih menggantungkan hidupnya dari sektor pertanian. Desa Pulosari memiliki prasarana transportasi darat yang tidak terlalu baik. Jalan aspal yang dimiliki oleh desa ini sepanjang 4,05 km dalam kondisi cukup baik, namun 4,45 km berkondisi rusak. Jalan aspal yang rusak ini cukup menghambat aktivitas penduduk di desa tersebut. Melalui kegiatan TMMD ke-113 ini, Satgas Kodim 0624/ Kab. Bandung, bersama Pemerintah Kabupaten Bandung di spot TMMD Desa Pulosari mengerjakan pembukaan jalan sepanjang 2 Km dengan lebar 7 meter yang menghubungkan Desa Polosari daengan Desa Margamekar, pengerasan jalan dengan lebar 5 meter sepanjang 2 km, dan pembuatan gorong-gorong di 4 titik sepanjang 4 meter. Selain sasaran fisik di atas, Satgas Kodim 0624/ Kab. Bandung, juga melaksanakan kegiatan non fisik berupa penyuluhan. Di antaranya tentang bela negara, wawasan kebangsaaan, Kamtibmas, hukum, bahaya narkoba, pertanian, perikanan dan masalah kesehatan yang berkaitan dengan stunting, posyandu dan Posbindu PTM. Pembangunan non fisik dilaksanakan sejalan dengan pembangunan fisik, terutama dalam membentengi masyarakat dari pengaruh negatif, merusak serta memecah belah. Dengan adanya TMMD serta penyuluhan yang dilakukan baik oleh Satgas TMMD maupun aparat terkait, akan menambah wawasan, membekali dan membentengi masyarakat. Juga akan menyadarkan tentang pentingnya bela negara serta kesatuan dan persatuan untuk menjaga keutuhan Negara Kesatuan Republik Indonesia dengan dasar Pancasila.
        
        Pengerasan dan pembangunan jalan sepanjang 2 Km dengan lebar 7 meter yang menghubungkan Desa Pulosari dan Desa Margamekar Kec. Pangalengan manfaat pembangunannya sangat membantu untuk kelancaran transportasi serta mendongkrak laju perekonomian bagi masyarakat di dua desa. Pelaksanaan TMMD ke 113 ini di apresiasi oleh beberapa masyarakat salah satunya Rukman Rukmansyah, S.Sos, M.Si seorang tokoh masyarakat, yang juga merupakan seorang aparat Kecamatan Pangalengan, sangat mengapresiasi pelaksanaan TMMD ke-113 TA 2022 Kodim 0624/Kab. Bandung ini. Asa warga masyarakat di dua desa akan sebuah akses jalan, kini telah dijawab melalui kegiatan TMMD ke-113 ini. “Dari sisi aspek sosial, TMMD telah membangkitkan harapan masyarakat yang tergolong daerah 3T, untuk perbaikan kualitas kehidupan juga perekonomiannya. Karena TMMD ini semakin membuka wawasan juga menstimulan dan mempelopori upaya perbaikan infra struktur. Semua itu dapat memfasilitasi dan merangsang perkembangan wawasan juga pertumbuhan ekonomi. Dengan demikan warga masyarakat lebih mudah dan cepat mendapatkan informasi juga melakukan kegiatan, dengan memanfaatkan fasilitas yang dibangun salah satu bentuknya adalah jalan, sehingga secara bertahap dan berkelanjutan akan ikut meningkatkan kesejahteraan masyarakat itu sendiri, termasuk menurunkan kesenjangan sosial dan tingkat kriminal,”. Begitu juga dengan kegiatan sasaran non fisik, pemerintahpun optimistis, bahwa rangkaian kegiatan penyuluhan yang dihelat juga akan meningkatkan, soliditas masyarakat, rasa persatuan dan kesatuan serta gotong royong. Sehinga akan mewujudkan Langit Biru di wilayah setempat, meningkatkan derajat kesehatan, serta berkurangnya angka kriminalitas.',
        'img' => 'https://1.bp.blogspot.com/-E1e9_iKizzw/YFsJwciJsWI/AAAAAAAAAiY/Mpi6u__Jebk-pban4VA3VOxRV5C2zGKyACLcBGAsYHQ/s263/no%2Bimage.JPG',
        'label' => 'Tmmd',
    ]);

    Tmmd::create([
        'title' => 'TNI Manunggal Membangun Desa (TMMD) Imbangan tahun 2023 Kodim 0624/Kab Bandung  di Kampung Babakan Desa Rawabogo Kecamatan Ciwidey.',
        'body' => 'Senin (29/05), lokasi Pra TMMD ditinjau langsung Dandim 0624/Kab Bandung, kedatangan Dandim disambut Pasiter Kapten Inf Yudi serta Danramil 2402/Cicalengka Kapten Inf Purwanto juga Kepala Desa Rawabogo Cecep Nunung Angga Prawira. Pembukaan kegiatan TNI Manunggal Membangun Desa (TMMD) Tahun 2023, yang dilaksanakan di Desa Rawabogo Kecamatan Ciwidey Kabupaten Bandung pada Selasa (13/6/3023) secara resmi dibuka oleh Bupati Bandung Dr. HM. Dadang Supriatna dengan dihadiri langsung Dandim 0624/Kabupaten Bandung Letkol Inf Hamzah Budi Susanto, turut hadir pula Kapolresta Bandung Kombes Pol Kusworo Wibowo, Bunda Bedas Kabupaten Bandung Hj. Emma Dety Dadang Supriatna, Kepala Dinas Pemberdayaan Masyarakat dan Desa (DPMD) Kabupaten Bandung H. Tata Irawan Sobandi, sejumlah Kepala Dinas dan Kepala Badan dari Organisasi Perangkat Daerah (OPD) Kabupaten Bandung, Forkopimcam Ciwidey, tokoh masyarakat dan sejumlah pihak lainnya hadir pula pada kegiatan pembukaan TMMD tersebut. 
        
        Sasaran pembangunan meliputi pengecoran jalan sepanjang 708 meter dengan lebar 3 meter serta Tanggul Penahan Tebing (TPT). Menurut Dandim 0624/Kab Bandung Letkol Inf Hamzah Budi Susanto jalan yang dilaksanakan TMMD ini merupakan akses jalan warga yang melintasi dua Kabupaten yaitu Kabupaten Bandung dan Kabupaten Bandung Barat. Bupati Dadang Supriatna mengatakan bahwa lokasi TMMD di Desa Rawabogo ini, berbatasan langsung dengan kawasan kehutanan, sehingga perlu akses jalan yang harus diperhatikan.
        
        Menurut Bupati Bandung saat penutupan TMDD di Ciwidey, Selasa (27/6/2023), tujuan kegiatan TMMD ini untuk membantu masyarakat dalam meningkatkan pembangunan sekaligus  meningkatkan pertumbuhan ekonomi masyarakat di desa yang terisolir maupun di perbatasan. Dalam pelaksanaannya berkolaborasi antara Pemkab Bandung dengan TNI. Kegiatan TNI Manunggal Membangun Desa (TMMD) di Desa Rawabogo Kecamatan Ciwidey Kabupaten Bandung, antara lain menghasilkan akses jalan baru yang menghubungkan antar desa maupun membuka akses untuk desa yang sebelumnya terisolir, meningkatkan pembangunan jalan sepanjang 708 meter dan lebar 3 meter, serta pembangunan tembok penahan tanah (TPT) dengan menelan anggaran cukup Rp 500 juta saja. Penutupan TNI Manunggal Membangun Desa (TMMD) Imbangan tahun 2023 Kodim 0624/Kab Bandung  di Kampung Babakan Desa Rawabogo Kecamatan Ciwidey ditandai dengan penandatanganan prasasti dilakukan oleh Bupati dan Dandim di Lokasi TMMD dengan disaksikan masyarakat setempat sebagai tanda telah selesainya pekerjaan yang dilakukan serta kesiapan hasil kerja untuk digunakan masyarakat. TMMD Imbangan Tahun 2023 berhasil menyelesaikan pembangunan jalan rabat beton sepanjang 708 meter dengan lebar 3 meter, tembok penahan tanah (TPT) sepanjang 90 meter dengan ketinggian 2.5 serta TPT sepanjang 22 meter dengan ketinggian 2 meter.',
        'img' => 'https://1.bp.blogspot.com/-E1e9_iKizzw/YFsJwciJsWI/AAAAAAAAAiY/Mpi6u__Jebk-pban4VA3VOxRV5C2zGKyACLcBGAsYHQ/s263/no%2Bimage.JPG',
        'label' => 'Tmmd',
    ]);
    }
}
